module.exports = {
    a2212: {label:"ALIMENTATION POUR ANIMAUX",empreinteCarbone:3},
    a6406: {label:"LIVRES DE POCHE",empreinteCarbone:3},
    a4206: {label:"FRUITS ET LEGUMES SECS",empreinteCarbone:3},
    a2800: {label:"SAURISSERIE LS",empreinteCarbone:3},
    a1000: {label:"FROMAGE COUPE",empreinteCarbone:3},
    a1002: {label:"FROMAGE LS PDV",empreinteCarbone:3},
    a4230: {label:"CHIPS",empreinteCarbone:0.36},
    a6050: {label:"EQUIPEMENT ACC AUTO",empreinteCarbone:3},
    a3006: {label:"BEURRE LS",empreinteCarbone:3},
    a6048: {label:"SPORTS/EQUIPEMENTS SPORTIF",empreinteCarbone:3},
    a210: {label:"TRIPERIE / ABATS TR",empreinteCarbone:3},
    a3002: {label:"FROMAGE LS",empreinteCarbone:0.4},
    a3000: {label:"ULTRA FRAIS",empreinteCarbone:3},
    a6232: {label:"TELEPHONIE",empreinteCarbone:3},
    a5018: {label:"SOUS VETEMENTS",empreinteCarbone:3},
    a6204: {label:"CUISSON PEM",empreinteCarbone:3},
    a5013: {label:"BIJOUTERIE HORLOGERIE",empreinteCarbone:3},
    a5012: {label:"ACCESSOIRES TEXTILE",empreinteCarbone:3},
    a5010: {label:"SEMELLE & ACC CHAUSSANT",empreinteCarbone:3},
    a230: {label:"TRIPERIE/ABATS LS PDV",empreinteCarbone:3},
    a4816: {label:"BEAUTE",empreinteCarbone:3},
    a5014: {label:"PETITE PUERICULTURE",empreinteCarbone:3},
    a6214: {label:"SON",empreinteCarbone:3},
    a4604: {label:"EAUX",empreinteCarbone:3},
    a6216: {label:"IMAGE",empreinteCarbone:3},
    a4606: {label:"VINS DE TABLE/PAYS",empreinteCarbone:3},
    a6210: {label:"BEAUTE / BIEN ETRE",empreinteCarbone:3},
    a4600: {label:"LIMONADES/SODA/SIROP/JUS DE FR",empreinteCarbone:3},
    a4602: {label:"BIERES ET CIDRES",empreinteCarbone:3},
    a6236: {label:"FILMS & PAP",empreinteCarbone:3},
    a4608: {label:"VINS SUPERIEURS ET VINS FINS",empreinteCarbone:3},
    a802: {label:"PRODUITS DE LA MER TRAD",empreinteCarbone:3},
    a244: {label:"VOLAILLES LS PDV",empreinteCarbone:3},
    a800: {label:"PRODUITS DE LA MER LS PDV",empreinteCarbone:3},
    a804: {label:"PR DE LA MER FRAIS EMBALLE",empreinteCarbone:3},
    a2002: {label:"STEACK HACHES LS",empreinteCarbone:3},
    a6026: {label:"ACCESSOIRES MENAGERS",empreinteCarbone:3},
    a4200: {label:"PRODUITS DU MONDE",empreinteCarbone:3},
    a6020: {label:"VAISSELLE - VERRERIE",empreinteCarbone:3},
    a4204: {label:"PATES ALIMENTAIRES",empreinteCarbone:3},
    a6024: {label:"FILTRES A CAFE/PORTE FILTRES",empreinteCarbone:3},
    a4208: {label:"POTAGES",empreinteCarbone:3},
    a6028: {label:"BOUGIE ENCENS BRIQUETS",empreinteCarbone:3},
    a5004: {label:"CHAUSSANT FEMME",empreinteCarbone:3},
    a6618: {label:"TIMBRE POSTE",empreinteCarbone:3},
    a5006: {label:"CHAUSSANT HOMME",empreinteCarbone:3},
    a5000: {label:"CHAUSSANT BEBE",empreinteCarbone:3},
    a5002: {label:"CHAUSSANT ENFANT",empreinteCarbone:3},
    a5008: {label:"MERCERIE",empreinteCarbone:3},
    a191: {label:"DECONSIGNES",empreinteCarbone:3},
    a4616: {label:"APERITIFS ALCOOLS",empreinteCarbone:3},
    a6220: {label:"STOCKAGES INFORMATIQUES",empreinteCarbone:3},
    a4809: {label:"PAPIERS HYGIENIQUES",empreinteCarbone:3},
    a4808: {label:"HYGIENE DU BEBE",empreinteCarbone:3},
    a4612: {label:"CHAMPAGNES",empreinteCarbone:3},
    a4610: {label:"MOUSSEUX",empreinteCarbone:3},
    a1004: {label:"FROMAGE FRAIS EMBALLE",empreinteCarbone:3},
    a4800: {label: "LAVAG DU LINGE",empreinteCarbone:3},
    a4806: {label:"HYGIENE FEMININE",empreinteCarbone:3},
    a4618: {label:"APERITIF / VIN DOUX",empreinteCarbone:3},
    a4804: {label:"EMBALLAGES / EPONGES",empreinteCarbone:3},
    a240: {label:"VOLAILLES TR",empreinteCarbone:3},
    a3008: {label:"MARGARINE/PATE A TARTINER",empreinteCarbone:3},
    a4212: {label:"EPICES ET POIVRES",empreinteCarbone:3},
    a6610: {label:"CARTES CADEAUX",empreinteCarbone:3},
    a4210: {label:"CONDIMENTS ET SAUCES",empreinteCarbone:3},
    a4216: {label:"HUILES",empreinteCarbone:3},
    a8200: {label:"PRESSE",empreinteCarbone:3},
    a4214: {label:"SELS",empreinteCarbone:3},
    a4218: {label:"VINAIGRES",empreinteCarbone:3},
    a6052: {label:"LUBRIFIANTS",empreinteCarbone:3},
    a5030: {label:"CONFECTION FEMME",empreinteCarbone:3},
    a5032: {label:"CONFECTION HOMME",empreinteCarbone:3},
    a6038: {label:"PLASTIQUE",empreinteCarbone:3},
    a5034: {label:"LINGE DE LIT",empreinteCarbone:3},
    a5036: {label:"LINGE D'OFFICE",empreinteCarbone:3},
    a6034: {label:"MENAGE/BROSSERIE",empreinteCarbone:1.53},
    a5038: {label:"LINGE EPONGE",empreinteCarbone:3},
    a6036: {label:"SECHANT / REPASSANT",empreinteCarbone:3},
    a6030: {label:"CUISSON MOULERIE",empreinteCarbone:3},
    a4614: {label:"FOIRE AUX VINS",empreinteCarbone:3},
    a6032: {label:"CADEAUX",empreinteCarbone:3},
    a4814: {label:"COTON",empreinteCarbone:3},
    a2004: {label:"UVC 21",empreinteCarbone:3},
    a6230: {label:"CONSOMMABLES INFORMATIQUES",empreinteCarbone:3},
    a4817: {label:"ACCESSOIRES COIFFANT/TOILETTE",empreinteCarbone:3},
    a4810: {label:"MOUCHOIR",empreinteCarbone:3},
    a2000: {label:"ELABORES SAUCISSERIE LS",empreinteCarbone:3},
    a4812: {label:"HYGIENE CORPORELLE HORS HOMME",empreinteCarbone:3},
    a4813: {label:"CAPILLAIRE HORS HOMME",empreinteCarbone:3},
    a4818: {label:"MAQUILLAGE",empreinteCarbone:3},
    a4802: {label:"ENTRETIEN",empreinteCarbone:3},
    a3600: {label:"FLEURS COUPEES",empreinteCarbone:3},
    a3602: {label:"PLANTES D INTERIEUR",empreinteCarbone:3},
    a3604: {label:"PLANTES D EXTERIEUR",empreinteCarbone:3},
    a6018: {label:"JOUETS PLEIN AIR",empreinteCarbone:3},
    a2400: {label:"VOLAILLES LS",empreinteCarbone:1.48},
    a232: {label:"PRODUITS ELABORES LS PDV",empreinteCarbone:3},
    a6228: {label:"ACC INFORMATIQUES",empreinteCarbone:3},
    a212: {label:"PRODUITS ELABORES TR",empreinteCarbone:3},
    a6008: {label:"DROGUERIE",empreinteCarbone:3},
    a5022: {label:"CHAUSSETTES/COLLANTS",empreinteCarbone:3},
    a1210: {label:"PATISSERIE SURGELEE TRAD",empreinteCarbone:3},
    a5020: {label:"COLLANTS MI-BAS",empreinteCarbone:3},
    a1212: {label:"PATISSERIE FRAÃŽCHE TRAD",empreinteCarbone:3},
    a5026: {label:"CONFECTION ENFANT FILLE/MIXTE",empreinteCarbone:3},
    a1214: {label:"PATISSERIE SURGELE LS PDV",empreinteCarbone:3},
    a5024: {label:"CONFEC LAYETTE FILLE / MIXTE",empreinteCarbone:3},
    a1216: {label:"PATISSERIE FRAICHE EMB LS PDV",empreinteCarbone:3},
    a6001: {label:"CADRES ET ALBUMS",empreinteCarbone:3},
    a6000: {label:"AMEUBLEMENT ET MOBILIER",empreinteCarbone:3},
    a6002: {label:"ECLAIRAGE PILE",empreinteCarbone:3},
    a6004: {label:"CARBURANTS ET COMBUSTIBLES",empreinteCarbone:3},
    a6046: {label:"MAROQUINERIE/BAGAGES",empreinteCarbone:3},
    a6006: {label:"BRICOLAGE",empreinteCarbone:3},
    a4820: {label:"DENTAIRE",empreinteCarbone:3},
    a4822: {label:"RASAGE FEMININ ET DEPILATOIRE",empreinteCarbone:3},
    a4824: {label:"EDT/EDC FEMMES ENFANTS",empreinteCarbone:3},
    a4826: {label:"HOMME",empreinteCarbone:3},
    a4828: {label:"PARAPHARMACIE",empreinteCarbone:3},
    a1208: {label:"VIENNOISERIE TRAD",empreinteCarbone:3},
    a4002: {label:"BISCUITERIE",empreinteCarbone:3},
    a4000: {label:"BISCOTTES ET PAINS GRILLES",empreinteCarbone:3},
    a4006: {label:"PETIT DEJEUNER/CACAO/CHOCOLAT",empreinteCarbone:3},
    a4004: {label:"CAFES/CHICOREE/EXTRAITS MALT",empreinteCarbone:3},
    a3204: {label:"VIENNOISERIE LS INDUS",empreinteCarbone:3},
    a3206: {label:"PRODUITS POUR GARNIR",empreinteCarbone:3},
    a4008: {label:"CEREALES ET BARRES CEREALIERES",empreinteCarbone:3},
    a3200: {label:"PAIN DE MIE",empreinteCarbone:0.23},
    a3202: {label:"PATISSERIE LS INDUS",empreinteCarbone:3},
    a3806: {label:"LEGUMES GEL",empreinteCarbone:3},
    a4032: {label:"COMPLEMENTS ALIMENTAIRES",empreinteCarbone:3},
    a3804: {label:"VIANDE GEL",empreinteCarbone:3},
    a6424: {label:"JEUX CONSOLES",empreinteCarbone:3},
    a3802: {label:"POISSON GEL",empreinteCarbone:3},
    a3800: {label:"TRAITEUR GEL",empreinteCarbone:3},
    a4222: {label:"CONSERVES DE POISSONS",empreinteCarbone:3},
    a4030: {label:"NUTRITION ET BIEN ETRE",empreinteCarbone:0.86},
    a3808: {label:"SURGELES GLACES",empreinteCarbone:3},
    a6428: {label:"ACCESSOIRES",empreinteCarbone:3},
    a1202: {label:"VIENNOISERIE LS PDV",empreinteCarbone:3},
    a1200: {label:"PAINS LS PDV",empreinteCarbone:3},
    a4220: {label:"CONSERVES DE LEGUMES",empreinteCarbone:3},
    a1206: {label:"PAINS SPECIAUX TRAD",empreinteCarbone:3},
    a1204: {label:"PAINS BLANCS / BOULANGERIE TR",empreinteCarbone:3},
    a6012: {label:"JARDINAGE",empreinteCarbone:3},
    a6010: {label:"PEINTURES & ACCESSOIRES",empreinteCarbone:3},
    a6016: {label:"PLEIN AIR - CAMPING",empreinteCarbone:3},
    a6014: {label:"ACCESSOIRES POUR ANIMAUX",empreinteCarbone:3},
    a4226: {label:"PLATS CUISINES ET A PREPARER",empreinteCarbone:3},
    a3404: {label:"F/L FRAIS EMBALLE",empreinteCarbone:3},
    a3012: {label: "LAIT S",empreinteCarbone:0.38},
    a8800: {label:"SERVICE CLEFS",empreinteCarbone:3},
    a4400: {label:"PRODUITS POUR ANIMAUX",empreinteCarbone:3},
    a6430: {label:"JOURNAUX PRESSE EXO",empreinteCarbone:3},
    a4018: {label:"CONFISERIE CHOCOLAT PAQUES",empreinteCarbone:0.63},
    a6068: {label:"PAPIERS",empreinteCarbone:3},
    a4014: {label:"CONFISERIE",empreinteCarbone:3},
    a6066: {label:"ECRIRE COLLER CORRIGER",empreinteCarbone:3},
    a4016: {label:"CONFISERIES CHOCOLATS NOEL",empreinteCarbone:3},
    a4010: {label:"THE & INFUSIONS",empreinteCarbone:3},
    a4012: {label:"CHOCOLATS TABLETTE",empreinteCarbone:3},
    a208: {label:"CHEVAL TR",empreinteCarbone:3},
    a224: {label:"PORC LS PDV",empreinteCarbone:3},
    a200: {label:"BOEUF TRAD",empreinteCarbone:3},
    a202: {label:"VEAU TR",empreinteCarbone:3},
    a5025: {label:"CONFECTION LAYETTE GARCON",empreinteCarbone:3},
    a204: {label:"PORC TR",empreinteCarbone:3},
    a206: {label:"AGNEAU / MOUTON TR",empreinteCarbone:3},
    a404: {label:"CHARCUTERIE FRAIS EMBALLE",empreinteCarbone:3},
    a402: {label:"CHARCUTERIE LS PDV",empreinteCarbone:3},
    a400: {label:"CHARCUTERIE TR",empreinteCarbone:3},
    a2600: {label:"CHARCUTERIE LS ET SALAISON",empreinteCarbone:3},
    a608: {label:"TRAITEUR FRAIS EMBALLE",empreinteCarbone:3},
    a2604: {label:"TRAITEUR LS",empreinteCarbone:3},
    a604: {label:"ROTISSERIE",empreinteCarbone:3},
    a600: {label:"TRAITEUR TRAD",empreinteCarbone:3},
    a602: {label:"TRAITEUR CHAUD",empreinteCarbone:3},
    a6078: {label:"CARTERIE",empreinteCarbone:3},
    a4028: {label:"ALIMENTATION POUR BEBE",empreinteCarbone:3},
    a4020: {label:"AIDE PATISSERIE ENTREMETS/GLAC",empreinteCarbone:3},
    a6070: {label:"CLASSEMENT",empreinteCarbone:0.56},
    a3410: {label:"F/L RAYON REFRIGERE DLC COURTE",empreinteCarbone:3},
    a4022: {label: "LAITSBOITES ET TUBES",empreinteCarbone:3},
    a6074: {label:"LOISIRS CREATIFS",empreinteCarbone:3},
    a4024: {label:"SUCRES",empreinteCarbone:0.18},
    a6076: {label:"CONDITIONNEMENTS CADEAUX",empreinteCarbone:3},
    a4026: {label:"CONFITURES-FRUITS AU SIROP",empreinteCarbone:3},
    a8000: {label:"GAZ",empreinteCarbone:3},
    a6404: {label:"BANDES DESSINEES",empreinteCarbone:3},
    a214: {label:"BOUCHERIE TR/LS PDV",empreinteCarbone:3},
    a6400: {label:"LITTERATURE",empreinteCarbone:3},
    a6402: {label:"DICO & PARA SCOLAIRE",empreinteCarbone:3},
    a4622: {label:"ALCOOL/EAUX DE VIE/LIQUEURS",empreinteCarbone:3},
    a4620: {label:"APERITIFS SANS ALCOOL",empreinteCarbone:3},
    a2206: {label:"AGNEAU / MOUTON LS",empreinteCarbone:3},
    a2204: {label:"PORC LS",empreinteCarbone:3},
    a2202: {label:"VEAU LS",empreinteCarbone:3},
    a6600: {label:"LIVRAISON",empreinteCarbone:3},
    a2200: {label:"BOEUF LS",empreinteCarbone:3},
    a3408: {label:"F/L RAYON REFRIGERE",empreinteCarbone:3},
    a4228: {label:"PRODUITS SALES APERITIFS",empreinteCarbone:3},
    a6042: {label:"JOUETS",empreinteCarbone:3},
    a3402: {label:"LEGUMES FRAIS",empreinteCarbone:3},
    a3014: {label:"OEUFS",empreinteCarbone:3},
    a3400: {label:"FRUITS FRAIS",empreinteCarbone:0.12},
    a6604: {label:"SACHERIE A VENDRE",empreinteCarbone:3},
    a3406: {label:"F/L LONGUE CONSERVATION",empreinteCarbone:3},
    a3010: {label:"CREMERIE FRAICHE",empreinteCarbone:3},
    a4034: {label:"EPICERIE FINE",empreinteCarbone:3},
    a4224: {label:"CONSERVES DE VIANDES",empreinteCarbone:3},
    a222: {label:"VEAU LS PDV",empreinteCarbone:3},
    a220: {label:"BOEUF LS PDV",empreinteCarbone:3},
    a226: {label:"AGNEAU/MOUTON LS PDV",empreinteCarbone:3},
    a6418: {label:"DVD",empreinteCarbone:3},
    a6022: {label:"VAISSELLE A JETER",empreinteCarbone:3},
    a6416: {label:"CD",empreinteCarbone:3},
    a228: {label:"CHEVAL LS PDV",empreinteCarbone:3},
    a6412: {label:"ACTIVITE COLORIAGE",empreinteCarbone:3},
    a6413: {label:"ALBUMS JEUNESSE",empreinteCarbone:3},
    a6410: {label:"VIE PRATIQUE",empreinteCarbone:3},
    a4202: {label:"FARINE/FECULE/SEMOULE/TAPIOCA",empreinteCarbone:3},
    a6202: {label:"PREPARATION CULINAIRE",empreinteCarbone:3},
    a6622: {label:"RECHARGE TELEPHONIQUE",empreinteCarbone:3},
    a6200: {label:"PETIT DEJEUNER",empreinteCarbone:3},
    a6207: {label:"TRAITEMENT DE L'EAU",empreinteCarbone:3},
    a6206: {label:"ENTRETIEN DU LINGE",empreinteCarbone:3},
    a6205: {label:"SACS ET ACC PEM",empreinteCarbone:3},
    a6620: {label:"DEVELOPPEMENT PHOTO",empreinteCarbone:3}
}